### ISSUE TITLE
Operation methods should not be bound to a particular instance

### ISSUE THREAD

**Issue by deescuderoo** [off-the-grid-inc/modular#4]
Right now we use `new(Int).Mul(a,b)` to multiply `a` and `b`, but it seems wasteful to create an instance of `Int` just to multiply other two elements. I propose to have methods for addition, multiplication and the other basic operations that is not tied to a particular instance, so we would write instead `modular.Mul(a,b)`.

**Comment by kassandraoftroy** [comment]
Note: I also agree that this is sensible and more personally intuitive. However this breaks structure with how big.Int implements these same methods... which is why I wanted everyone chiming in. Here are other people debating the same issue:
https://stackoverflow.com/questions/13514082/why-is-big-int-api-in-go-so-strange

**Comment by alvatar** [comment]
The accepted answer in StackOverflow explains it well. I think we should continue with the same API.
